Анеля Дусаева, Task 7
Ane1y/formal-lang-course pull request #5
Opened 2023-04-06 22:33 UTC by Ane1y

2023-04-07 14:06 UTC, rustam-azimov requested changes

2023-04-07 14:06 UTC, rustam-azimov commented on project/task7/RecursiveFA.py
> +class RecursiveFA:
Сразу добавьте возможность получать матрицы смежности конечных автоматов.

2023-04-07 14:06 UTC, rustam-azimov commented on project/task7/ecfg.py
> +class ExtendedContextFreeGrammatic:
добавить везде докстринги

2023-04-10 13:02 UTC, Ane1y commented on project/task7/RecursiveFA.py
> +class RecursiveFA:
исправлено, док стринги добавила

2023-04-13 10:22 UTC, rustam-azimov approved these changes

2023-06-16 13:34 UTC, merged